[workspace]
members = [
    "packages/cosmos",
    "packages/cosmos-bin",
    # "packages/prost-build",
]
resolver = "2"

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0
