[package]
name = "cosmos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", default-features = false }
tonic = { version = "0.11.0", features = [
    "channel",
    "tls",
    "tls-roots",
    "codegen",
    "prost"
], default-features = false }
cosmos-sdk-proto = { version = "0.21.1", features = ["cosmwasm"] }
prost = "0.12.4"
prost-types = "0.12.4"
bech32 = "0.11.0"
bitcoin = "0.32.0"
hkd32 = { version = "0.7.0", features = ["bip39"] }
once_cell = "1.19.0"
rand = "0.8.5"
tracing = "0.1.40"
fs-err = "2.11.0"
serde = "1"
serde_json = "1"
chrono = "0.4.38"
hex = "0.4"
sha2 = "0.10.8"
reqwest = { version = "0.12.4", default-features = false, features = ["json"] }
base64 = "0.22.1"
parking_lot = "0.12.2"
clap = { version = "4.5.4", features = ["derive", "env"], optional = true }
bip39 = "2"
thiserror = "1.0.59"
tiny-keccak = { version = "2.0", features = ["keccak"] }
http = "0.2.11"
cosmwasm-std = "2.0.2"
flate2 = { version = "1.0.30", features = ["zlib"] }
strum = "0.26.2"
strum_macros = "0.26.2"
tendermint-proto = "0.35.0"

[features]
clap = ["dep:clap"]
default = ["rustls-tls", "compression"]
compression = ["reqwest/gzip", "reqwest/brotli"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dev-dependencies]
quickcheck = "1"
