[package]
name = "cosmos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", default-features = false }
tonic = { version = "0.12.3", features = [
    "channel",
    "tls",
    "tls-roots",
    "codegen",
    "prost"
], default-features = false }
cosmos-sdk-proto = { version = "0.26.0", features = ["cosmwasm"] }
prost = "0.13.3"
prost-types = "0.13.3"
bech32 = "0.11.0"
bitcoin = "0.32.4"
once_cell = "1.20.2"
rand = "0.8.5"
tracing = "0.1.40"
fs-err = "3.0.0"
serde = "1.0.214"
serde_json = "1.0.132"
chrono = "0.4.38"
hex = "0.4"
sha2 = "0.10.8"
reqwest = { version = "0.12.9", default-features = false, features = ["json"] }
base64 = "0.22.1"
parking_lot = "0.12.3"
clap = { version = "4.5.20", features = ["derive", "env"], optional = true }
bip39 = "2.1.0"
thiserror = "2.0.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
http = "1.1.0"
cosmwasm-std = ">=1.5.3, <3"
flate2 = { version = "1.0.34", features = ["zlib"] }
strum = "0.26.3"
strum_macros = "0.26.4"
tendermint-proto = "0.40.0"
figment = { version = "0.10.19", features = ["env", "toml"], optional = true }
directories = { version = "5.0.1", optional = true }
toml = { version = "0.8.19", optional = true }
secp256k1 = { version = "0.30", features = ["hashes"] }

[features]
clap = ["dep:clap"]
config = ["dep:figment", "dep:directories", "dep:toml"]
default = ["rustls-tls", "compression"]
compression = ["reqwest/gzip", "reqwest/brotli"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
directories = ["dep:directories"]
toml = ["dep:toml"]

[dev-dependencies]
quickcheck = "1"
