[package]
name = "cosmos-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4"
anyhow = { version = "1.0.69", features = ["backtrace"] }
cosmos = { path = "../cosmos", features = ["clap", "compression", "rustls-tls"], default-features = false }
tokio = { version = "1.25.0", features = ["full"] }
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
futures = "0.3.26"
tracing = "0.1.39"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1"
once_cell = "1.17.1"
fs-err = "2"
base64 = "0.21"
cw3 = "1"
cw3-flex-multisig = "1"
cw4 = "1"
cw4-group = "1"
cw-utils = "1"
cosmwasm-std = "1"
csv = "1.3.0"

[dev-dependencies]
quickcheck = "1"

[[bin]]
name = "cosmos"
path = "src/main.rs"
