[package]
name = "cosmos-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive", "env"] }
clap_complete = "4.5.37"
anyhow = { version = "1.0.93", features = ["backtrace"] }
cosmos = { path = "../cosmos", features = ["clap", "compression", "rustls-tls", "config"], default-features = false }
tokio = { version = "1.41.1", features = ["full"] }
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
futures = "0.3.31"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1.11.1"
once_cell = "1.20.2"
fs-err = "3.0.0"
base64 = "0.22.1"
cw3 = "2.0.0"
cw3-flex-multisig = "2.0.0"
cw4 = "2.0.0"
cw4-group = "2.0.0"
cw-utils = "2.0.0"
cosmwasm-std = "2.1.4"
csv = "1.3.0"

[dev-dependencies]
quickcheck = "1"

[[bin]]
name = "cosmos"
path = "src/main.rs"
