[workspace]
resolver = "2"

[package]
name = "prost-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic-build = "0.12.3"
anyhow = "1.0.71"
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"
reqwest = "0.11.17"

[dev-dependencies]

[[bin]]
name = "prost-build"
path = "src/main.rs"
