name: Rust

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.10.0
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77.2
          components: clippy, rustfmt
      - name: Compile workspace
        run: just cargo-compile
      - name: Build workspace
        run: just build-app
      - name: Lint
        run: |
          just cargo-clippy-check
          just cargo-fmt-check
      - name: Tests
        run: just cargo-test
